#!/bin/bash

################################################################################
#                                                                              #
#              🚀 DOCKER DEPLOYMENT - COPY & PASTE COMMANDS                  #
#                                                                              #
#  Copy and paste these commands into your terminal to deploy DNA-Stego      #
#                                                                              #
################################################################################

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║           🐳 DNA-Stego Docker Deployment Commands              ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 1: TEST LOCALLY (5 minutes)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Copy and paste these commands:"
echo ""
echo -e "${GREEN}# Navigate to project${NC}"
echo "cd /path/to/dna-stego"
echo ""
echo -e "${GREEN}# Create .env from template${NC}"
echo "cp .env.production .env"
echo ""
echo -e "${GREEN}# Start Docker containers${NC}"
echo "docker-compose up --build"
echo ""
echo "Wait for output:"
echo "  backend    | INFO:     Uvicorn running on http://0.0.0.0:8000"
echo "  frontend   | VITE v7.3.1  ready in 234 ms"
echo ""
echo "Then test in browser:"
echo "  Frontend: http://localhost:5173"
echo "  Backend:  http://localhost:8000/health"
echo ""
echo "Stop with: Ctrl+C"
echo "Cleanup:   docker-compose down"
echo ""
echo "✅ If both work → Proceed to Step 2"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 2: SETUP PRODUCTION ENVIRONMENT (5 minutes)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}# Create production environment file${NC}"
echo "cp .env.production .env.prod"
echo ""
echo -e "${GREEN}# Edit with your values (use: nano .env.prod)${NC}"
echo "# Change these values:"
echo "#   DATABASE_URL=postgresql://postgres:PASSWORD@db.PROJECT.supabase.co:5432/postgres"
echo "#   VITE_API_URL=https://yourdomain.com"
echo "#   ALLOWED_ORIGINS=https://yourdomain.com"
echo "#   SECRET_KEY=<generate: openssl rand -hex 32>"
echo "#   JWT_SECRET=<generate: openssl rand -hex 32>"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 3: DEPLOY TO SERVER (10 minutes)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}# SSH into your server${NC}"
echo "ssh root@YOUR_SERVER_IP"
echo ""
echo -e "${GREEN}# Install Docker on server${NC}"
echo "sudo apt update"
echo "sudo apt install -y docker.io docker-compose"
echo ""
echo -e "${GREEN}# Clone your repository${NC}"
echo "cd /home/ubuntu"
echo "git clone https://github.com/YOUR_USERNAME/dna-stego.git"
echo "cd dna-stego"
echo ""
echo -e "${GREEN}# Create .env.prod on server${NC}"
echo "nano .env.prod  # Paste your environment variables"
echo ""
echo -e "${GREEN}# Create storage directories${NC}"
echo "mkdir -p storage/fasta_files storage/temp logs"
echo ""
echo -e "${GREEN}# Start production containers${NC}"
echo "docker-compose -f docker-compose.prod.yml build"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo -e "${GREEN}# Verify containers are running${NC}"
echo "docker-compose -f docker-compose.prod.yml ps"
echo ""
echo -e "${GREEN}# Test services${NC}"
echo "curl http://localhost:8000/health"
echo "curl http://localhost:3000"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 4: SETUP SSL & DOMAIN (5 minutes)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}# Install Certbot for SSL${NC}"
echo "sudo apt install certbot python3-certbot-nginx -y"
echo ""
echo -e "${GREEN}# Get SSL certificate from Let's Encrypt${NC}"
echo "sudo certbot certonly --standalone -d yourdomain.com -d www.yourdomain.com"
echo ""
echo -e "${GREEN}# Point your domain to server IP${NC}"
echo "# Go to your DNS provider and set:"
echo "#   A record: @ → YOUR_SERVER_IP"
echo "#   A record: www → YOUR_SERVER_IP"
echo ""
echo -e "${GREEN}# Or use Cloudflare (recommended, FREE)${NC}"
echo "# 1. Go to https://www.cloudflare.com"
echo "# 2. Add your domain"
echo "# 3. Point nameservers to Cloudflare"
echo "# 4. Cloudflare handles DNS"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 5: VERIFY DEPLOYMENT${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}# Test from server${NC}"
echo "curl http://localhost:8000/health"
echo "curl http://localhost:3000"
echo ""
echo -e "${GREEN}# View logs${NC}"
echo "docker-compose -f docker-compose.prod.yml logs -f"
echo ""
echo -e "${GREEN}# Check containers status${NC}"
echo "docker-compose -f docker-compose.prod.yml ps"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}DEPLOYMENT COMPLETE! 🎉${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Your application is now running at:"
echo "  Frontend: https://yourdomain.com"
echo "  Backend:  https://yourdomain.com/api"
echo ""
echo "Maintenance commands:"
echo ""
echo -e "${GREEN}# View logs${NC}"
echo "docker-compose -f docker-compose.prod.yml logs -f"
echo ""
echo -e "${GREEN}# Stop containers${NC}"
echo "docker-compose -f docker-compose.prod.yml down"
echo ""
echo -e "${GREEN}# Update application (new deployment)${NC}"
echo "git pull"
echo "docker-compose -f docker-compose.prod.yml build"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo -e "${GREEN}# Check resource usage${NC}"
echo "docker stats"
echo ""
echo -e "${GREEN}# Backup database${NC}"
echo "pg_dump \$DATABASE_URL > backup_\$(date +%Y%m%d).sql"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}QUICK REFERENCE${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Using automated script:"
echo ""
echo -e "${GREEN}# Test locally${NC}"
echo "./docker-deploy.sh local"
echo ""
echo -e "${GREEN}# Deploy to production${NC}"
echo "./docker-deploy.sh prod"
echo ""
echo -e "${GREEN}# Stop all containers${NC}"
echo "./docker-deploy.sh stop"
echo ""
echo -e "${GREEN}# View logs${NC}"
echo "./docker-deploy.sh logs backend"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}FOR MORE DETAILS, SEE:${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  📖 DOCKER_STEPS.md      - Detailed step-by-step guide"
echo "  📖 DOCKER_DEPLOYMENT.md - Complete reference with troubleshooting"
echo "  📖 DOCKER_READY.md      - Overview and checklist"
echo ""
echo "Server provider links:"
echo "  DigitalOcean: https://www.digitalocean.com (Recommended: \$12/mo)"
echo "  Hetzner:      https://www.hetzner.com      (Budget: €3.99/mo)"
echo "  Vultr:        https://www.vultr.com        (Value: \$6/mo)"
echo "  AWS EC2:      https://aws.amazon.com/ec2/  (Premium: \$26/mo)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
